package com.gafipro.gafiscript.security;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;

public final class ScriptBytecodeValidator {
    /*
     * javac emits java/lang/invoke references for ordinary Java lambdas
     * (invokedynamic + LambdaMetafactory). These references are compiler
     * implementation details, not by themselves a permission to call the
     * invoke API directly.
     *
     * Direct use of java.lang.invoke remains blocked by ScriptSecurity,
     * including MethodHandles/Unsafe-style escape hatches.
     */
    private static final List<String> BLOCKED_TOKENS = List.of(
            "java/io/",
            "java/net/",
            "java/nio/file/",
            "java/lang/reflect/",
            "java/lang/Runtime",
            "java/lang/ProcessBuilder",
            "java/lang/ClassLoader",
            "sun/",
            "jdk/internal/",
            "ProcessBuilder",
            "URLClassLoader",
            "Unsafe"
    );

    private ScriptBytecodeValidator() {}

    public static Validation validateDirectory(Path directory) {
        try (var stream = Files.walk(directory)) {
            for (Path classFile :
                    stream.filter(Files::isRegularFile)
                            .filter(path -> path.toString().endsWith(".class"))
                            .toList()) {

                byte[] bytes = Files.readAllBytes(classFile);
                String latin =
                        new String(bytes, StandardCharsets.ISO_8859_1)
                                .toLowerCase(Locale.ROOT);

                for (String blocked : BLOCKED_TOKENS) {
                    if (latin.contains(blocked.toLowerCase(Locale.ROOT))) {
                        return Validation.fail(
                                "Bytecode contains blocked reference '" +
                                blocked +
                                "' in " +
                                directory.relativize(classFile)
                        );
                    }
                }
            }

            return Validation.ok();
        } catch (IOException exception) {
            return Validation.fail(
                    "Could not inspect generated bytecode: " +
                    exception.getMessage()
            );
        }
    }

    public record Validation(
            boolean valid,
            String message
    ) {
        static Validation ok() {
            return new Validation(true, "");
        }

        static Validation fail(String message) {
            return new Validation(false, message);
        }
    }
}
